### ISSUE TITLE
Failed in `Setup`

### ISSUE THREAD

**Issue by oOhyeahh** [luigibertaco/spike-k8s-instances-mngmt#1]
I try to follow the step up but it failed in this point. 
```
➜  instances_management git:(main) kind create cluster --config deploy/cluster.yaml
ERROR: failed to create cluster: error reading file: open deploy/cluster.yaml: no such file or directory
```

**Comment by luigibertaco** [comment]
I noticed that you are in a folder named `instances_management` but the root folder is supposed to be `instances-management`, I checked the steps again and it worked for me. 

Just check if you are executing it from the root folder (correct) instead of the module `instances_management` (incorrect)

**Comment by oOhyeahh** [comment]
@luigibertaco Thanks! I should copy the command from Readme. It works for me now.
